### ISSUE TITLE
relation to prodigy

### ISSUE THREAD

**Issue by kidd** [emacs-pe/honcho.el#1]
Hello,

I love there's diversity and multiple ways of doing things in opensource. As a prodigy user, I think it'd be good if you added some text about differences and similarities between the two.

Thanks!

**Comment by marsam** [comment]
Hi:

Sorry for the late response, I've only used `prodigy.el` briefly, so this comparison might be biased.

The main difference between both packages, is how they start the process.

-   prodigy.el uses [`start-process`](https://github.com/rejeep/prodigy.el/blob/67b74d1/prodigy.el#L1035) to start a process, and prodigy handles the process filter/sentinel itself. This has some advantages, for instance it can handle retries, and timeouts; and drawbacks, handle [output filters](https://github.com/rejeep/prodigy.el/blob/67b74d1/prodigy.el#L838-L842) itself (e.g. currently does not handle backspace control character `^H`), and given that `start-process` is not aware of `default-directory` (i.e TRAMP support), it has to handle how to start a [processs with sudo itself](https://github.com/rejeep/prodigy.el/blob/67b74d1/prodigy.el#L994-L1006).

-   honcho.el instead uses [`compilation-mode`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation-Mode.html) to start a process. `compilation-mode` is shipped with Emacs, is `default-directory`-aware, and can be extended to handle [ANSI control characters](https://github.com/atomontage/xterm-color). Using compilation mode simplifies a lot the process management. For instance, if you want to start a python server in a docker container with `www-data` user.
    
    ```elisp
    (honcho-define-service python-server
      :cwd     "/docker:mycontainer:/app/"
      :sudo    "www-data"
      :command ("python" "-m" "http.server")
      :env     (("ENVIRONMENT" . "development")))
    ```

From a user perspective, both packages can be used almost indistinctly. `prodigy.el` also offers other features that `honcho.el` currently doesn't have e.g. service tags.

I hope the above is useful to you, please let me know if you have any questions.

**Comment by Fuco1** [comment]
I have a branch opened on prodigy that adds support for handling the ansi escapes (up/down/left/right, delete line, backspace) which should cover most of the need.  I tried briefly to use compilation mode but it's too difficult to bolt it on top of something that goes the `start-process` way.

Tramp support can be quite easily added by swapping it for `start-file-process` which uses very similar API.
